"""Initial migration

Revision ID: 772a8434f699
Revises: 
Create Date: 2025-06-10 21:54:23.136175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772a8434f699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.drop_column('avatar')
        pass
    # ### end Alembic commands ###
