"""add missing league columns

Revision ID: fc07f91e53bb
Revises: 87835fa7871a
Create Date: 2025-06-06 17:47:44.134487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc07f91e53bb'
down_revision = '87835fa7871a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_teams', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draft_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('point_system', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('commissioner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_leagues_commissioner_id', 'users', ['commissioner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leagues_commissioner_id', type_='foreignkey')
        batch_op.drop_column('commissioner_id')
        batch_op.drop_column('status')
        batch_op.drop_column('point_system')
        batch_op.drop_column('draft_type')
        batch_op.drop_column('max_teams')

    # ### end Alembic commands ###
